---
- name: Set up systemd override
  when: ansible_service_mgr == "systemd"
  block:

    - name: Ensure the override directory exists (systemd)
      ansible.builtin.file:
        name: /etc/systemd/system/dnsdist.service.d
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Override the dnsdist service (systemd)
      ansible.builtin.template:
        src: override-service.systemd.conf.j2
        dest: /etc/systemd/system/dnsdist.service.d/override.conf
        owner: root
        group: root
        mode: 0644
      when: dnsdist_service_overrides != {}
      notify: Reload systemd and restart dnsdist

    - name: Override the dnsdist unit (systemd)
      ansible.builtin.template:
        src: override-unit.systemd.conf.j2
        dest: /etc/systemd/system/dnsdist.service.d/override-unit.conf
        owner: root
        group: root
        mode: 0644
      when: dnsdist_unit_overrides != {}
      notify: Reload systemd and restart dnsdist

    - name: Override the dnsdist environments (systemd)
      ansible.builtin.template:
        src: override-environment.systemd.conf.j2
        dest: /etc/systemd/system/dnsdist.service.d/override-environment.conf
        owner: root
        group: root
        mode: 0644
      when: dnsdist_environment_overrides != {}
      notify: Reload systemd and restart dnsdist

- name: Add the dnsdist configuration
  tags:
    - molecule-idempotence-notest
  ansible.builtin.template:
    src: dnsdist.conf.j2
    dest: "{{ default_dnsdist_config_location }}"
    owner: "{{ _dnsdist_owner }}"
    group: "{{ _dnsdist_group }}"
    mode: 0640
    validate: dnsdist -C %s --check-config 2>&1
  notify: Restart dnsdist

- name: Add the dnsdist additional configuration files
  tags:
    - molecule-idempotence-notest
  ansible.builtin.copy:
    content: "{{ dnsdist_config_files[item] }}"
    dest: "{{ default_dnsdist_config_location | dirname }}/{{ item }}"
    owner: "{{ _dnsdist_owner }}"
    group: "{{ _dnsdist_group }}"
    mode: 0640
  with_items: "{{ dnsdist_config_files }}"
  notify: Restart dnsdist
