---
- name: Install gnupg
  ansible.builtin.package:
    name: gnupg
    state: present

- name: Ensure keyring directory exists.
  ansible.builtin.file:
    name: '/etc/apt/keyrings'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download the dnsdist APT Repository key
  ansible.builtin.get_url:
    url: "{{ dnsdist_install_repo['gpg_key_url'] }}"
    dest: "/etc/apt/keyrings/{{ dnsdist_install_repo['gpg_key_file'] }}"
    owner: root
    group: root
    mode: '0644'
  notify: Update the APT cache
  
- name: Create the dnsdist APT repository Deb822 source
  ansible.builtin.template:
    src: 'dnsdist.sources.j2'
    dest: "/etc/apt/sources.list.d/dnsdist_install_repo['name'].sources"
    owner: root
    group: root
    mode: '0644'
  notify: Update the APT cache

- name: Pin the dnsdist APT Repository
  ansible.builtin.template:
    src: dnsdist.pin.j2
    dest: /etc/apt/preferences.d/dnsdist
    mode: u=rw,g=r,o=r
