---
- name: Install python3-debian (required by deb822_repository)
  ansible.builtin.package:
    name: python3-debian
    state: present

- name: Add the dnsdist APT Repository (Deb822-style)
  ansible.builtin.deb822_repository:
    name: "{{ dnsdist_install_repo['name'] }}"
    types: deb
    uris: "http://{{ dnsdist_install_repo['apt_repo_origin'] }}/{{ ansible_distribution | lower }}/"
    suites: "{{ ansible_distribution_release | lower }}-{{ dnsdist_install_repo['apt_version'] }}"
    components: main
    architectures: "{{ _dnsdist_apt_architecture }}"
    signed_by: "{{ dnsdist_install_repo['gpg_key_url'] }}"
  notify: Update the APT cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Pin the dnsdist APT Repository
  ansible.builtin.template:
    src: dnsdist.pin.j2
    dest: /etc/apt/preferences.d/dnsdist
    mode: u=rw,g=r,o=r
